1. Read Raw Data .xlsx, then take some predetermined columns

In [1]:
import pandas as pd 

path = "D:/Personal/Project/World Energy/Dataset/Raw Data/owid-energy-data.xlsx"
df = pd.read_excel(path, usecols=["country", "iso_code", "year", "population", "gdp", "hydro_elec_per_capita", "hydro_electricity", "hydro_consumption"])

df.head()

,country,year,iso_code,population,gdp,hydro_consumption,hydro_elec_per_capita,hydro_electricity
0,ASEAN (Ember),2000,NaN,NaN,NaN,NaN,NaN,50.450001
1,ASEAN (Ember),2001,NaN,NaN,NaN,NaN,NaN,54.330002
2,ASEAN (Ember),2002,NaN,NaN,NaN,NaN,NaN,53.290001
3,ASEAN (Ember),2003,NaN,NaN,NaN,NaN,NaN,53.209999
4,ASEAN (Ember),2004,NaN,NaN,NaN,NaN,NaN,52.990002

2. Set year 1974 - 2024

In [2]:
df = df[(df['year'] >= 1974) & (df['year'] <= 2024)]

df.head()

,country,year,iso_code,population,gdp,hydro_consumption,hydro_elec_per_capita,hydro_electricity
0,ASEAN (Ember),2000,NaN,NaN,NaN,NaN,NaN,50.450001
1,ASEAN (Ember),2001,NaN,NaN,NaN,NaN,NaN,54.330002
2,ASEAN (Ember),2002,NaN,NaN,NaN,NaN,NaN,53.290001
3,ASEAN (Ember),2003,NaN,NaN,NaN,NaN,NaN,53.209999
4,ASEAN (Ember),2004,NaN,NaN,NaN,NaN,NaN,52.990002

3. Handle missing value and for feature "population" & "gdp", interpolate and fill the data.

In [3]:
def clean_data(df):
    # Drop rows with missing data in column: 'iso_code'
    df = df.dropna(subset=['iso_code'])
    df[['population', 'gdp']] = (
                df.groupby('country')[['population', 'gdp']]
                .transform(lambda x: x.interpolate())
                .bfill()
                .ffill()
            )
    # Replace missing values with 0 in column: 'hydro_consumption'
    df = df.fillna({'hydro_consumption': 0})
    # Replace missing values with 0 in column: 'hydro_elec_per_capita'
    df = df.fillna({'hydro_elec_per_capita': 0})
    # Replace missing values with 0 in column: 'hydro_electricity'
    df = df.fillna({'hydro_electricity': 0})
    return df

df_clean = clean_data(df.copy())
df_clean.head()

,country,year,iso_code,population,gdp,hydro_consumption,hydro_elec_per_capita,hydro_electricity
99,Afghanistan,1974,AFG,12469127.0,1.430911e+10,0.0,0.0,0.0
100,Afghanistan,1975,AFG,12773966.0,1.517777e+10,0.0,0.0,0.0
101,Afghanistan,1976,AFG,13059861.0,1.602360e+10,0.0,0.0,0.0
102,Afghanistan,1977,AFG,13340758.0,1.520736e+10,0.0,0.0,0.0
103,Afghanistan,1978,AFG,13611444.0,1.633783e+10,0.0,0.0,0.0

4. Export to excel file

In [4]:
df_clean.to_excel("clean_data_hydro.xlsx", index=False)

print("File completed saved!")

File completed saved!